import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Signup from '../components/Signup';
import Login from '../components/Login';
import Forgot from '../components/Forgot';
import styles from '../styles/Home.module.css';
import { Button } from 'semantic-ui-react';
import { useState } from 'react';

export default function Home() {
  const [show, setShow] = useState('');
  const handleShow = (str) => {
    setShow(str);
  };
  return (
    <>
      <Head>
        <title>Intelligent Crazy People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.header}>
        <Navbar />
        <div className={styles.landing_bg}></div>

        <div className={styles.container}>
          {/* 1 */}
          <div className={styles.tagline}>
            <h2 className={styles.h2}>
              Building friendships across disciplines
              <br />
              <code className={styles.code}>2000 members</code> and{' '}
              <code className={styles.code}>~15000 applications</code>
            </h2>
          </div>
          {/* 2 */}
          {show === '' ? (
            <div className={styles.wrap}>
              <div className={styles.button_wrap}>
                <Button
                  onClick={() => handleShow('Signup')}
                  className={styles.button}
                  content="apply"
                  primary
                />
                <Button
                  onClick={() => handleShow('Login')}
                  className={styles.button}
                  content="login"
                  landing-secondary
                />
              </div>
            </div>
          ) : show === 'Signup' ? (
            <Signup openL={() => handleShow('Login')} />
          ) : show === 'Login' ? (
            <Login
              openS={() => handleShow('Signup')}
              openF={() => handleShow('Forgot')}
            />
          ) : show === 'Forgot' ? (
            <Forgot openS={() => handleShow('Signup')} />
          ) : null}
        </div>
      </div>
    </>
  );
}
