import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import styles from '../styles/Home.module.css';
import { Button } from 'semantic-ui-react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Intelligent Crazy People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.header}>
        <Navbar />
        <div className={styles.landing_bg}></div>

        <div className={styles.container}>
          {/* 1 */}
          <div className={styles.tagline}>
            <h2 className={styles.h2}>
              Building friendships across disciplines
              <br />
              <code className={styles.code}>2000 members</code> and{' '}
              <code className={styles.code}>~15000 applications</code>
            </h2>
          </div>
          {/* 2 */}
          <div className={styles.wrap}>
            <div className={styles.button_wrap}>
              <Button className={styles.button} content="apply" primary />
              <Button className={styles.button} content="login" landing-secondary />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
